data_cfg:
  dataset_name: GREW
  dataset_root: your_path
  dataset_partition: ./datasets/GREW/GREW.json
  num_workers: 5
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: GREW

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 200000
  save_name: SwinGait3D_GREW_bz20
  sampler:
    batch_shuffle: false
    batch_size: 8
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 720 # limit the number of sampled frames to prevent out of memory
  eval_func: evaluate_real_scene #GREW_submission
  metric: euc # cos
  transform:
    - type: BaseSilCuttingTransform

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: SwinGait
  Backbone:
    mode: p3d
    in_channels: 1
    layers:
      - 1
      - 4
      - 4
      - 2
    channels:
      - 64
      - 128
  bin_num: 
    - 15
  SeparateBNNecks:
    in_channels: 256
    class_num: 20000
    parts_num: 16

optimizer_cfg:
  lr: 0.0003
  solver: AdamW
  weight_decay: 0.02

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 100000000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: false #true # half_percesion float for memory reduction and speedup
  fix_BN: false
  wandb: false
  log_iter: 1000
  with_test: true
  optimizer_reset: True
  restore_ckpt_strict: false
  restore_hint: your_path_deepgaitv2_model
  save_iter: 20000
  save_name: SwinGait3D_GREW
  sync_BN: true
  T_max_iter: 150000
  total_iter: 200000
  sampler:
    batch_shuffle: true
    batch_size:
      - 32 # TripletSampler, batch_size[0] indicates Number of Identity
      - 4 #                 batch_size[1] indicates Samples sequqnce for each Identity
    frames_num_fixed: 30 # fixed frames number for training
    frames_skip_num: 4
    sample_type: fixed_ordered # fixed control input frames number, unordered for controlling order of input tensor; Other options: unfixed_ordered or all_ordered
    type: TripletSampler
  transform:
    - type: Compose
      trf_cfg:
        - type: RandomPerspective
          prob: 0.2
        - type: BaseSilTransform
        - type: RandomHorizontalFlip
          prob: 0.2
        - type: RandomRotate
          prob: 0.2


